### ISSUE TITLE
Page not found at /accounts/login/

### ISSUE THREAD

**Issue by baltasvejas** [omab/psa-passwordless#1] opened 2014-07-08 11:15 UTC
I have installed and ran the example provided.
After I enter an e-mail, I am being redirected to /accounts/login and get an errror:

Page not found (404)
Request Method: GET
Request URL:    http://localhost:8000/accounts/login/
Using the URLconf defined in app.urls, Django tried these URL patterns, in this order:
^$ [name='home']
^done/$ [name='done']
^login-form/$ [name='login_form']
^validation-sent/$ [name='validation_sent']
^token-login/(?P<token>[^/]+)/$ [name='token_login']
^logout/$ [name='logout']
^login/(?P<backend>[^/]+)/$ [name='begin']
^complete/(?P<backend>[^/]+)/$ [name='complete']
^disconnect/(?P<backend>[^/]+)/$ [name='disconnect']
^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$ [name='disconnect_individual']
The current URL, accounts/login/, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

Does it mean I should add /accounts/login/ url myself? (as well as view and template)
Or I did something wrong?

**Comment by omab** [comment] 2014-07-08 16:57
That's probably the default value for `LOGIN_REDIRECT_URL`, you can define the setting `LOGIN_REDIRECT_URL = '/'` and that should do the trick.

**Comment by baltasvejas** [comment] 2014-07-08 17:11
Hm... I can't check with test server now remotely, but on my other project I actually have these settings such as `LOGIN_REDIRECT_URL = '/members'` and `SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/done/'`, but still I get the same issue.
I will check tomorrow and will come back.

**Comment by omab** [comment] 2014-07-08 17:31
@baltasvejas, so that sounds like an error in the auth process, try defining `LOGIN_ERROR_URL` too.

**Comment by baltasvejas** [comment] 2014-07-08 18:12
I have defined `LOGIN_ERROR_URL = '/error/'` and accordingly made entries in urls.py, views.py and error.html template.
1. I enter my e-mail and later get login url sent to my inbox;
2. I follow in e-mail provided url and get redirected to error page.
However I do not know how to catch exceptions in order to get more debug info.

**Comment by omab** [comment] 2014-08-14 16:58
@baltasvejas, sorry about the huge delay, I've pushed a fix for the issue, I wasn't able to reproduce it because the PSA version I have installed in the `virtualenv` was outdated.

**Closed as completed by omab** 2014-08-14 16:58 UTC
